export const allPositions: string[] = [
	'CEO',
	'CFO',
	'CTO',
	'CIO',
	'CMO',
	'COO',
	'Director de Recursos Humanos',
	'Director de Marketing',
	'Director de Operaciones',
	'Gerente de Proyectos',
	'Ingeniero de Software',
	'Analista de Datos',
	'Especialista en Recursos Humanos',
	'Especialista en Marketing',
	'Especialista en Operaciones',
	'Especialista en Soporte Técnico',
	'Especialista en Ventas',
]
