---
name: Deploy
on:
  workflow_dispatch:
    inputs:
      tf_environment:
        type: choice
        options: [production]
        default: production
        description: Ambiente al cual se desplegará la aplicación
        required: true
env:
  AWS_REGION: us-east-1
  S3_BUCKET: app.hgio.co
  NODE_ENV: production
jobs:
  upload_to_s3:
    name: Upload to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-${{ github.job }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install node dependencies
        run: npm ci --include dev
      - name: Check Lint and Format
        run: npm run code-check
      - name: Export static files
        run: npx ng build -c ${{ inputs.tf_environment }}
      - name: Upload application to S3
        run: aws s3 sync ./dist/appinstruments-web-app s3://$S3_BUCKET --delete
