---
name: Pull request
on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}
env:
  AWS_REGION: us-east-1
jobs:
  build_application:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install node dependencies
        run: npm ci --include dev
      - name: Check Lint and Format
        run: npm run code-check
      - name: Build application
        run: npx ng build
